### ISSUE TITLE
Implement lockdown mode

### ISSUE THREAD

**Issue by ghost** [Epictek/VoidBot#5]
**Is your feature request related to a problem? Please describe.**

Not at all.

**Describe the solution you'd like**

A lockdown mode incase a raid ever were to happen & it'd basically lockdown the entire server except for the rank "Void Users" and above.

i.e. It would lock all the channels (nobody except "Void users" and above being able to talk) 

**Describe alternatives you've considered**

Manually locking down the server, which would take too long.

**Comment by Epictek** [comment]
This is already achieved by the verification system implemented by Valk bot which I hope to implement in VoidBot soon

**Comment by 0ae** [comment]
> This is already achieved by the verification system implemented by Valk bot which I hope to implement in VoidBot soon

Fair enough
